---
sudo: required

language: python
python: "2.7"

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq

install:
  # Install Vagrant
  - sudo apt-get install vagrant

  # Install Ansible.
  - pip install ansible

script:
  # validate vagrantfile
  - vagrant validate
  # check syntax
  - ansible-playbook docker_cli/docker.yml --syntax-check
  # check before install
  - ansible-playbook docker_cli/docker.yml --check
  # install
  - ansible-playbook docker_cli/docker.yml
