---
sudo: required

language: python
python: "2.7"

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq

install:
  # Install Virtualbox 5.1
  - wget http://download.virtualbox.org/virtualbox/5.1.30/virtualbox-5.1_5.1.30-118389~Ubuntu~xenial_amd64.deb
  - sudo dpkg -i virtualbox-5.1_5.1.30-118389~Ubuntu~xenial_amd64.deb
  # Install Vagrant
  - wget https://releases.hashicorp.com/vagrant/2.0.0/vagrant_2.0.0_x86_64.deb
  - sudo dpkg -i vagrant_2.0.0_x86_64.deb
  #- sudo dpkg --install - <(curl -o- https://releases.hashicorp.com/vagrant/2.0.0/vagrant_2.0.0_x86_64.deb)

  # Install Ansible.
  - pip install ansible

script:
  # validate vagrantfile syntax
  - vagrant validate
  # check playbook syntax
  - ansible-playbook docker_cli/docker.yml --syntax-check
