- hosts: all
  gather_facts: false
  become: yes
  roles:
    - install-tools
  tags:
    - install-tools

- hosts: all
  gather_facts: true
  become: yes
  roles:
    - install-packages
  tags:
    - install-packages
